FROM pytorch/pytorch:2.5.1-cuda12.1-cudnn9-runtime
RUN apt update &&  apt install -y --no-install-recommends default-jre
WORKDIR /workspace
COPY . .
RUN pip3 install -r requirements.txt --no-cache-dir
EXPOSE 8080
EXPOSE 8081
EXPOSE 8082
CMD ["torchserve", "--start", "--ts-config=config.properties", "--model-store", "model_store", "--models", "sd3=sd3.mar", "--disable-token-auth", "--ncs", "--enable-model-api"]