FROM node:16
WORKDIR /workspace
# Copy package.json and package-lock.json to the working directory
COPY . .
# Install project dependencies
RUN npm install

# Build the UI application
RUN npm run build
EXPOSE 3000
CMD  "npm run dev"